const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let messages=[],memories=[],suggestion=null,scope='shared',category='All',editing=null,nextId=20,toastTimer;const categories=['All','Money','Plans','To-Dos','Recommendations','Dates','Decisions'];
function init(){messages=[{id:1,text:'Hey! Still up for Tiong Bahru this Saturday?',mine:false,time:'12:36'},{id:2,text:'Yes! Coffee at 11? Let’s meet at the MRT exit.',mine:true,time:'12:37'},{id:3,text:'Perfect, 11 it is ☕ Also, you should try Plain Vanilla. The banana bread is so good.',mine:false,time:'12:38'},{id:4,text:'Adding that to the list! And I’ll book the dinner table for Saturday.',mine:true,time:'12:39'},{id:5,text:'Thanks for covering lunch earlier btw!',mine:false,time:'12:41'},{id:6,text:'No worries, it was $25 for your share.',mine:true,time:'12:41'},{id:7,text:'I’ll transfer you the $25 on Friday 👍',mine:false,time:'12:42'}];memories=[{id:10,title:'Coffee with Jamie',category:'Plans',detail:'Saturday, 10 Oct · 11:00 AM · Tiong Bahru MRT',scope:'shared',source:2,resolved:false},{id:11,title:'Try Plain Vanilla',category:'Recommendations',detail:'Jamie recommends the banana bread.',scope:'shared',source:3,resolved:false},{id:12,title:'Book the dinner table',category:'To-Dos',detail:'You · Saturday, 10 Oct',scope:'shared',source:4,resolved:false}];suggestion={title:'Jamie owes you $25',category:'Money',detail:'Friday, 9 Oct · Lunch repayment',source:7};scope='shared';category='All';$('#show-resolved').checked=false;renderMessages();renderSuggestion();renderMemories();scrollBottom()}
function scrollBottom(){requestAnimationFrame(()=>{$('#chat-scroll').scrollTop=$('#chat-scroll').scrollHeight})}
function renderMessages(){ $('#messages').innerHTML=messages.map(m=>`<div class="message ${m.mine?'mine':''}" id="message-${m.id}"><button class="bubble" data-message="${m.id}" aria-label="Remember message: ${esc(m.text)}">${esc(m.text)}</button><time>${esc(m.time)}${m.mine?' · ✓✓':''}</time></div>`).join('')}
function renderSuggestion(){ $('#suggestion').innerHTML=suggestion?`<div class="suggestion-top"><span>✧</span> Suggested memory <span class="tag ${esc(suggestion.category)}">${esc(suggestion.category)}</span></div><h3>${esc(suggestion.title)}</h3><p>${esc(suggestion.detail)}</p><div class="suggestion-actions"><button class="primary" id="confirm-suggestion">✓ Confirm</button><button class="secondary" id="edit-suggestion">Edit</button><button class="dismiss" id="dismiss-suggestion">Dismiss</button></div>`:''}
function renderMemories(){const active=memories.filter(m=>m.scope==='shared'&&!m.resolved).length;$('#header-count').textContent=active;$('#shared-count').textContent=memories.filter(m=>m.scope==='shared').length;$('#private-count').textContent=memories.filter(m=>m.scope==='private').length;document.querySelectorAll('[data-scope]').forEach(b=>b.classList.toggle('active',b.dataset.scope===scope));$('#scope-note').textContent=scope==='shared'?'Confirmed together, kept in one place.':'A little space for things only you want to keep.';$('#privacy-note').textContent=scope==='shared'?'Shared items are visible to you and Jamie in this demo.':'Remembered items are private to you in this demo.';$('#filters').innerHTML=categories.map(c=>`<button class="${c===category?'active':''}" data-filter="${c}">${c}</button>`).join('');const resolved=$('#show-resolved').checked;const items=memories.filter(m=>m.scope===scope&&(category==='All'||m.category===category)&&m.resolved===resolved);$('#items-label').textContent=`${items.length} ${resolved?'resolved':'active'} memor${items.length===1?'y':'ies'}`;$('#memory-list').innerHTML=items.length?items.map(m=>`<article class="memory-card ${m.resolved?'resolved':''}"><div class="card-top"><span class="tag ${esc(m.category)}">${esc(m.category)}</span><button class="icon-button" data-edit="${m.id}" aria-label="Edit ${esc(m.title)}" title="Edit memory">⋯</button></div><h3>${esc(m.title)}</h3><p>${esc(m.detail)||'No extra details'}</p><button class="source-button" data-source="${m.source}">↳ View original message</button><div class="card-action"><span>${scope==='shared'?'Shared with Jamie':'Only you'}</span><button data-resolve="${m.id}">${m.resolved?'↶ Reopen':m.category==='Money'?'✓ Mark paid':m.category==='Recommendations'?'✓ Mark tried':'✓ Complete'}</button></div></article>`).join(''):`<div class="empty"><b>${resolved?'Nothing resolved yet':scope==='private'&&category==='All'?'Keep a little something.':'All clear here.'}</b>${scope==='private'&&!resolved?'Click a chat message to save it privately.':resolved?'Completed memories will appear here.':'Try another category or confirm a suggestion in the chat.'}</div>`}
function notify(t){clearTimeout(toastTimer);$('#toast').textContent=t;$('#toast').classList.add('show');toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3000)}
function showEditor(item,mode){editing={...item,mode};$('#memory-title').value=item.title;$('#memory-category').value=item.category||'Plans';$('#memory-detail').value=item.detail||'';$('#memory-scope').value=item.scope||'shared';$('#edit-title').textContent=mode==='edit'?'Make it yours.':mode==='suggestion'?'Check the important bit.':'Keep the important bit.';$('#visibility-label').hidden=mode==='suggestion';$('#edit-dialog').showModal();$('#memory-title').focus()}
function openPanel(){ $('#memory-panel').classList.add('open') }
function addMessage(text,mine){const m={id:nextId++,text,mine,time:'12:43'};messages.push(m);renderMessages();scrollBottom();return m}
function saveSuggestion(){if(!suggestion)return;memories.push({...suggestion,id:nextId++,scope:'shared',resolved:false});suggestion=null;renderSuggestion();renderMemories();notify('Added to shared memory · You and Jamie');}
const scenarios={money:{text:'I’ll pay you $18 for the movie tickets on Monday.',title:'Jamie owes you $18',category:'Money',detail:'Monday, 5 Oct · Movie tickets'},plans:{text:'Let’s check out the National Gallery on Sunday at 2pm?',title:'Visit the National Gallery',category:'Plans',detail:'Sunday, 11 Oct · 2:00 PM'},task:{text:'Can you send me the photos from our trip by Tuesday?',title:'Send Jamie the trip photos',category:'To-Dos',detail:'You · Tuesday, 6 Oct'}};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.close){$('#'+b.dataset.close).close();return}if(b.dataset.message){const m=messages.find(m=>m.id===Number(b.dataset.message));const selected=window.getSelection().toString().trim();showEditor({title:selected&&m.text.includes(selected)?selected:m.text,category:'Plans',scope:'private',source:m.id},'manual')}if(b.dataset.scope){scope=b.dataset.scope;category='All';renderMemories()}if(b.dataset.filter){category=b.dataset.filter;renderMemories()}if(b.dataset.resolve){const m=memories.find(m=>m.id===Number(b.dataset.resolve));m.resolved=!m.resolved;renderMemories();notify(m.resolved?(m.category==='Money'?'Marked as paid':'Memory completed')+' · Find it under Resolved':'Memory reopened')}if(b.dataset.edit){const m=memories.find(m=>m.id===Number(b.dataset.edit));showEditor(m,'edit')}if(b.dataset.source){const el=$('#message-'+b.dataset.source);if(innerWidth<=1100)$('#memory-panel').classList.remove('open');el.scrollIntoView({behavior:'smooth',block:'center'});el.classList.add('highlight');setTimeout(()=>el.classList.remove('highlight'),2400)}if(b.dataset.scenario){if(suggestion){notify('Confirm or dismiss the current suggestion first.');$('#suggestion').scrollIntoView({behavior:'smooth',block:'nearest'});return}const s=scenarios[b.dataset.scenario],m=addMessage(s.text,false);suggestion={...s,source:m.id};renderSuggestion();scrollBottom()}if(b.id==='confirm-suggestion')saveSuggestion();if(b.id==='edit-suggestion')showEditor({...suggestion,scope:'shared'},'suggestion');if(b.id==='dismiss-suggestion'){suggestion=null;renderSuggestion();notify('Suggestion dismissed. The message stays in your chat.')}if(['how','tips'].includes(b.id))$('#help-dialog').showModal();if(b.id==='open-memory'){openPanel();$('#memory-panel').scrollTop=0}if(b.id==='close-memory')$('#memory-panel').classList.remove('open');if(b.id==='reset')$('#reset-dialog').showModal();if(b.id==='confirm-reset'){$('#reset-dialog').close();init();notify('Fresh conversation. Ready to try again.')}if(b.id==='theme-toggle'){toggleTheme()}});
$('#show-resolved').addEventListener('change',renderMemories);
$('#edit-form').addEventListener('submit',e=>{e.preventDefault();const title=$('#memory-title').value.trim();if(!title){$('#memory-title').setCustomValidity('Add a short title for this memory.');$('#memory-title').reportValidity();return}const item={title,category:$('#memory-category').value,detail:$('#memory-detail').value.trim(),scope:editing.mode==='suggestion'?'shared':$('#memory-scope').value,source:editing.source};if(editing.mode==='edit'){Object.assign(memories.find(m=>m.id===editing.id),item)}else{memories.push({...item,id:nextId++,resolved:false})}if(editing.mode==='suggestion'){suggestion=null;renderSuggestion()}scope=item.scope;category='All';$('#show-resolved').checked=false;renderMemories();$('#edit-dialog').close();openPanel();notify(item.scope==='private'?'Saved to Remembered · Only you':'Saved to shared memory')});$('#memory-title').addEventListener('input',()=>$('#memory-title').setCustomValidity(''));
$('#send-form').addEventListener('submit',e=>{e.preventDefault();const input=$('#message-input'),t=input.value.trim();if(!t)return;const m=addMessage(t,true);input.value='';if(!suggestion){let cat=/\$|pay|owe|transfer|dollar/i.test(t)?'Money':/recommend|try|cafe|restaurant|watch/i.test(t)?'Recommendations':/birthday|anniversary/i.test(t)?'Dates':/decided|agreed|decision/i.test(t)?'Decisions':/send|book|bring|remind|finish/i.test(t)?'To-Dos':/meet|let.s|tomorrow|friday|saturday|sunday/i.test(t)?'Plans':null;if(cat){suggestion={title:t,category:cat,detail:'From your message · Review the details before saving',source:m.id};renderSuggestion()}else notify('Message added. Click it to remember something.')}else notify('Message added to this demo conversation.');scrollBottom()});
document.addEventListener('keydown',e=>{if(e.key==='Escape')$('#memory-panel').classList.remove('open')});init();

/* Theme preference is independent of the resettable demo conversation. */
const themeToggle = $('#theme-toggle');
const systemTheme = window.matchMedia('(prefers-color-scheme: dark)');
function applyTheme(theme) {
  const dark = theme === 'dark';
  document.documentElement.dataset.theme = theme;
  themeToggle.setAttribute('aria-pressed', String(dark));
  themeToggle.title = dark ? 'Switch to light mode' : 'Switch to dark mode';
  document.querySelector('meta[name="theme-color"]').content = dark ? '#121722' : '#3158e7';
}
applyTheme(document.documentElement.dataset.theme || 'light');
function toggleTheme() {
  const theme = document.documentElement.dataset.theme === 'dark' ? 'light' : 'dark';
  applyTheme(theme);
  try { localStorage.setItem('keeps-theme', theme); } catch (_) {}
}
systemTheme.addEventListener('change', event => {
  let saved;
  try { saved = localStorage.getItem('keeps-theme'); } catch (_) {}
  if (saved !== 'dark' && saved !== 'light') applyTheme(event.matches ? 'dark' : 'light');
});
window.addEventListener('storage', event => {
  if (event.key === 'keeps-theme' || event.key === null) {
    const theme = event.newValue;
    applyTheme(theme === 'dark' || theme === 'light' ? theme : systemTheme.matches ? 'dark' : 'light');
  }
});
